MASTER_FILE = 'https://margincalculator.angelbroking.com/OpenAPI_File/files/OpenAPIScripMaster.json'

MASTER_FILE_PATH = '/opt/tmp/angel_1/{}_OpenAPIScripMaster.json'
STOP_CHECK = '/opt/tmp/angel_1/stop.txt'
STOPPED = '/opt/tmp/angel_1/stop.txt.stopped'

XCHANGE_NSE = 'NSE'
XCHANGE_BSE = 'BSE'

SEGMENT_NSE_FNO = 'NFO'

TYPE_BUY = 'BUY'
TYPE_SELL = 'SELL'

ORDER_MARKET = 'MARKET'
ORDER_LIMIT = 'LIMIT'

PRODCUT_TYPE_CARRY_FORWARD = 'CARRYFORWARD'

VARIETY_AMO = 'AMO'
VARIETY_NORMAL = 'NORMAL'

INSTRUMENT_NSE_OPTION_IDX = 'OPTIDX'
INSTRUMENT_NSE_OPTION_STK = 'OPTSTK'

INSTRUMENT_NSE_FUT_IDX = 'FUTIDX'
INSTRUMENT_NSE_FUT_STK = 'FUTSTK'

INTERVAL_1_MIN = 'ONE_MINUTE'
INTERVAL_3_MIN = 'THREE_MINUTE'

DATE_FORMAT_FULL_HISTROIC_CANDLE_ = '%Y-%M-%d %H:%M'
DATE_FORMAT_DAY_HISTROIC_CANDLE = '%Y-%M-%d'
DATE_FORMAT_START_TIME = '09:15'
DATE_FORMAT_END_TIME = '15:30'

ALLOWED_ORDER_STATUS = ['open', 'complete', 'cancelled', 'rejected']

ANGEL_1_BSE = 'ANGEL_1_BSE'
ANGEL_1_NSE = 'ANGEL_1_NSE'
